# Generated by Django 5.1.4 on 2024-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_creado_en_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('Aseo', 'Aseo'), ('Despensa', 'Despensa'), ('Congelados', 'Congelados'), ('Cuidado Personal', 'Cuidado Personal')], max_length=16),
        ),
    ]
