# Generated by Django 5.1.4 on 2024-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_tipo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
