# Generated by Django 5.1.4 on 2024-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Aseo', 'Aseo'), ('Despensa', 'Despensa'), ('Congelados', 'Congelados'), ('Cuidado Personal', 'Cuidado Personal')], max_length=16),
        ),
    ]
